import React from 'react';
import Link from 'gatsby-link';
import Template from '../../../components/templates/LoreExtractAction';
import Markdown from '../../../components/Markdown';
import CodeTabs from '../../../components/CodeTabs';
import CodeTab from '../../../components/CodeTab';
import QuickstartBranch from '../../../components/QuickstartBranch';

export default (props) => {
  return (
    <Template>
      <h1>
        extract action
      </h1>
      <p>
        CLI command to extract one or more of the <Link to="/actions/">actions</Link> generated by the framework
        into your project. This will allow you to see the code that gets executed, and change it if needed.
      </p>

      <h3>
        Usage
      </h3>
      <p>
        To use this command, you need to specify the name of the model you'd like to extract an action for, as well
        as the name of the action you'd like to extract.
      </p>

      <Markdown type="sh" text={`
      lore extract action [model]/[action]
      `}/>

      <p>
        For example, to extract the <code>create</code> action for the <code>post</code> model, you would run the
        command <code>lore extract action post/create</code>.
      </p>
      <p>
        If you do NOT specify an action, the command will extract ALL actions for that model. For example, this
        command:
      </p>

      <Markdown type="sh" text={`
      lore extract action post
      `}/>

      <p>
        Will extract all actions for the <code>post</code> model, and create the files below:
      </p>

      <Markdown type="sh" text={`
      -src
       |-actions
         |-post
           |-create.js
           |-destroy.js
           |-find.js
           |-get.js
           |-update.js
      `}/>
    </Template>
  )
};
